---
- name: Install nginx
  pacman:
    name: nginx

- name: Create sites-available and sites-enabled
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
  with_items:
    - sites-enabled
    - sites-available

- name: Copy nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Enable nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
